"""
All historical snapshots migrated from adm_basis_tracker.jsx and mendota_basis_tracker.jsx.
Run seed_db() once to populate the SQLite database.
"""
from database import init_db, upsert_snapshot

# ── helpers ──────────────────────────────────────────────────────────────────
def spot(grain, dm, sym, basis):
    return {"id": f"SPOT_{grain[:2].upper()}", "grain": grain, "deliveryMonth": dm,
            "futuresSymbol": sym, "basisCents": basis, "isSpot": True, "spotGrain": grain}

def row(rid, grain, dm, sym, basis):
    return {"id": rid, "grain": grain, "deliveryMonth": dm,
            "futuresSymbol": sym, "basisCents": basis, "isSpot": False}

# ── ADM Decatur ───────────────────────────────────────────────────────────────
ADM_DECATUR = [
    {
        "timestamp": "2025-05-23T20:38:48.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSN25",15),
            row("SB_MAY","Soybeans","MAY","ZSN25",15),
            row("SB_JUN","Soybeans","JUN","ZSN25",20),
            row("SB_JUL","Soybeans","JUL","ZSN25",20),
            row("SB_OCT","Soybeans","OCT","ZSX25",-20),
            row("SB_NOV","Soybeans","NOV","ZSX25",-5),
            row("SB_DEC","Soybeans","DEC","ZSF26",-5),
            row("SB_JAN","Soybeans","JAN","ZSF26",0),
            row("SB_FEB","Soybeans","FEB","ZSH26",2),
            row("SB_MAR","Soybeans","MAR","ZSH26",8),
            row("CN_MAY","Corn","MAY","ZCN25",4),
            row("CN_JUN","Corn","JUN","ZCN25",5),
            row("CN_JUL","Corn","JUL","ZCN25",11),
            row("CN_OCT","Corn","OCT","ZCZ25",-15),
            row("CN_NOV","Corn","NOV","ZCZ25",-7),
            row("CN_DEC","Corn","DEC","ZCZ25",-5),
        ],
    },
    {
        "timestamp": "2026-04-24T20:44:37.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSK26",28),
            row("SB_MAY","Soybeans","MAY","ZSK26",28),
            row("SB_JUN","Soybeans","JUN","ZSN26",10),
            row("SB_JULFH","Soybeans","JUL FH","ZSN26",15),
            row("SB_JULLH","Soybeans","JUL LH","ZSN26",8),
            row("SB_OCT","Soybeans","OCT","ZSX26",-10),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",0),
            row("SB_JAN","Soybeans","JAN","ZSF27",5),
            row("SB_FEB","Soybeans","FEB","ZSH27",12),
            row("SB_MAR","Soybeans","MAR","ZSH27",15),
            row("CN_MAY","Corn","MAY","ZCK26",10),
            row("CN_JUN","Corn","JUN","ZCN26",5),
            row("CN_JUL","Corn","JUL","ZCN26",3),
            row("CN_OCT","Corn","OCT","ZCZ26",-10),
            row("CN_DEC","Corn","DEC","ZCZ26",5),
            row("CN_JAN","Corn","JAN","ZCH27",-2),
            row("CN_FEB","Corn","FEB","ZCH27",1),
            row("CN_MAR","Corn","MAR","ZCH27",4),
        ],
    },
    {
        "timestamp": "2026-05-14T20:44:30.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSN26",20),
            row("SB_MAY","Soybeans","MAY","ZSN26",20),
            row("SB_JUN","Soybeans","JUN","ZSN26",20),
            row("SB_JULFH","Soybeans","JUL FH","ZSN26",20),
            row("SB_JULLH","Soybeans","JUL LH","ZSN26",12),
            row("SB_OCT","Soybeans","OCT","ZSX26",-10),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",-3),
            row("SB_JAN","Soybeans","JAN","ZSF27",2),
            row("SB_FEB","Soybeans","FEB","ZSH27",5),
            row("SB_MAR","Soybeans","MAR","ZSH27",5),
            row("SB_APR","Soybeans","APR","ZSK27",5),
            row("SB_MAY27","Soybeans","MAY '27","ZSK27",5),
            row("SB_JUN27","Soybeans","JUN '27","ZSN27",0),
            row("SB_JUL27","Soybeans","JUL '27","ZSN27",0),
            row("CN_MAY","Corn","MAY","ZCN26",10),
            row("CN_JUN","Corn","JUN","ZCN26",8),
            row("CN_JUL","Corn","JUL","ZCN26",8),
            row("CN_OCT","Corn","OCT","ZCZ26",-10),
            row("CN_DEC","Corn","DEC","ZCZ26",5),
            row("CN_JAN","Corn","JAN","ZCH27",-5),
            row("CN_FEB","Corn","FEB","ZCH27",-3),
            row("CN_MAR","Corn","MAR","ZCH27",0),
        ],
    },
    {
        "timestamp": "2026-05-20T20:43:39.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSN26",25),
            row("SB_MAY","Soybeans","MAY","ZSN26",25),
            row("SB_JUN","Soybeans","JUN","ZSN26",20),
            row("SB_JULFH","Soybeans","JUL FH","ZSN26",20),
            row("SB_JULLH","Soybeans","JUL LH","ZSN26",12),
            row("SB_OCT","Soybeans","OCT","ZSX26",-10),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",-3),
            row("SB_JAN","Soybeans","JAN","ZSF27",2),
            row("SB_FEB","Soybeans","FEB","ZSH27",5),
            row("SB_MAR","Soybeans","MAR","ZSH27",5),
            row("SB_APR","Soybeans","APR","ZSK27",5),
            row("SB_MAY27","Soybeans","MAY '27","ZSK27",5),
            row("SB_JUN27","Soybeans","JUN '27","ZSN27",0),
            row("SB_JUL27","Soybeans","JUL '27","ZSN27",0),
            row("CN_MAY","Corn","MAY","ZCN26",12),
            row("CN_JUN","Corn","JUN","ZCN26",8),
            row("CN_JUL","Corn","JUL","ZCN26",8),
            row("CN_OCT","Corn","OCT","ZCZ26",-10),
            row("CN_DEC","Corn","DEC","ZCZ26",5),
            row("CN_JAN","Corn","JAN","ZCH27",-5),
            row("CN_FEB","Corn","FEB","ZCH27",-3),
            row("CN_MAR","Corn","MAR","ZCH27",0),
        ],
    },
    {
        "timestamp": "2026-05-21T20:45:54.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSN26",25),
            row("SB_MAY","Soybeans","MAY","ZSN26",25),
            row("SB_JUN","Soybeans","JUN","ZSN26",20),
            row("SB_JULFH","Soybeans","JUL FH","ZSN26",20),
            row("SB_JULLH","Soybeans","JUL LH","ZSN26",12),
            row("SB_OCT","Soybeans","OCT","ZSX26",-10),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",-3),
            row("SB_JAN","Soybeans","JAN","ZSF27",2),
            row("SB_FEB","Soybeans","FEB","ZSH27",5),
            row("SB_MAR","Soybeans","MAR","ZSH27",5),
            row("SB_APR","Soybeans","APR","ZSK27",5),
            row("SB_MAY27","Soybeans","MAY '27","ZSK27",5),
            row("SB_JUN27","Soybeans","JUN '27","ZSN27",0),
            row("SB_JUL27","Soybeans","JUL '27","ZSN27",0),
            row("CN_MAY","Corn","MAY","ZCN26",12),
            row("CN_JUN","Corn","JUN","ZCN26",8),
            row("CN_JUL","Corn","JUL","ZCN26",8),
            row("CN_OCT","Corn","OCT","ZCZ26",-10),
            row("CN_DEC","Corn","DEC","ZCZ26",5),
            row("CN_JAN","Corn","JAN","ZCH27",-5),
            row("CN_FEB","Corn","FEB","ZCH27",-3),
            row("CN_MAR","Corn","MAR","ZCH27",0),
        ],
    },
    {
        "timestamp": "2026-05-22T20:43:46.000Z", "provider": "ADM", "location": "ADM Decatur",
        "rows": [
            spot("Soybeans","MAY","ZSN26",25),
            row("SB_MAY","Soybeans","MAY","ZSN26",25),
            row("SB_JUN","Soybeans","JUN","ZSN26",20),
            row("SB_JULFH","Soybeans","JUL FH","ZSN26",20),
            row("SB_JULLH","Soybeans","JUL LH","ZSN26",12),
            row("SB_OCT","Soybeans","OCT","ZSX26",-10),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",-3),
            row("SB_JAN","Soybeans","JAN","ZSF27",2),
            row("SB_FEB","Soybeans","FEB","ZSH27",5),
            row("SB_MAR","Soybeans","MAR","ZSH27",5),
            row("SB_APR","Soybeans","APR","ZSK27",5),
            row("SB_MAY27","Soybeans","MAY '27","ZSK27",5),
            row("SB_JUN27","Soybeans","JUN '27","ZSN27",0),
            row("SB_JUL27","Soybeans","JUL '27","ZSN27",0),
            row("CN_MAY","Corn","MAY","ZCN26",12),
            row("CN_JUN","Corn","JUN","ZCN26",8),
            row("CN_JUL","Corn","JUL","ZCN26",8),
            row("CN_OCT","Corn","OCT","ZCZ26",-10),
            row("CN_DEC","Corn","DEC","ZCZ26",5),
            row("CN_JAN","Corn","JAN","ZCH27",-5),
            row("CN_FEB","Corn","FEB","ZCH27",-3),
            row("CN_MAR","Corn","MAR","ZCH27",0),
        ],
    },
]

# ── ADM Cedar Rapids ──────────────────────────────────────────────────────────
ADM_CEDAR_RAPIDS = [
    {
        "timestamp": "2025-05-23T20:38:42.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCN25",0),
            row("CN_MAY","Corn","MAY","ZCN25",0),
            row("CN_JUN","Corn","JUN","ZCN25",-3),
            row("CN_JUL","Corn","JUL","ZCN25",-3),
            row("CN_AUG","Corn","AUG","ZCU25",-20),
            row("CN_SEP","Corn","SEP","ZCU25",-20),
            row("CN_OCT","Corn","OCT","ZCZ25",-23),
            row("CN_NOV","Corn","NOV","ZCZ25",-20),
            row("CN_DEC","Corn","DEC","ZCZ25",-17),
            row("CN_JAN","Corn","JAN","ZCH26",-20),
            row("CN_FEB","Corn","FEB","ZCH26",-17),
            row("CN_MAR","Corn","MAR","ZCH26",-14),
        ],
    },
    {
        "timestamp": "2026-04-24T20:44:30.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCK26",-10),
            row("CN_MAY","Corn","MAY","ZCK26",-10),
            row("CN_JUN","Corn","JUN","ZCN26",-9),
            row("CN_JUL","Corn","JUL","ZCN26",-7),
            row("CN_AUG","Corn","AUG","ZCU26",-15),
            row("CN_SEP","Corn","SEP","ZCU26",-15),
            row("CN_OCT","Corn","OCT","ZCZ26",-22),
            row("CN_NOV","Corn","NOV","ZCZ26",-20),
            row("CN_DEC","Corn","DEC","ZCZ26",-17),
            row("CN_JAN","Corn","JAN","ZCH27",-20),
            row("CN_FEB","Corn","FEB","ZCH27",-18),
            row("CN_MAR","Corn","MAR","ZCH27",-16),
        ],
    },
    {
        "timestamp": "2026-05-14T20:44:30.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCN26",-17),
            row("CN_MAY","Corn","MAY","ZCN26",-17),
            row("CN_JUN","Corn","JUN","ZCN26",-18),
            row("CN_JUL","Corn","JUL","ZCN26",-15),
            row("CN_AUG","Corn","AUG","ZCU26",-15),
            row("CN_SEP","Corn","SEP","ZCU26",-15),
            row("CN_OCT","Corn","OCT","ZCZ26",-24),
            row("CN_NOV","Corn","NOV","ZCZ26",-22),
            row("CN_DEC","Corn","DEC","ZCZ26",-15),
            row("CN_JAN","Corn","JAN","ZCH27",-18),
            row("CN_FEB","Corn","FEB","ZCH27",-16),
            row("CN_MAR","Corn","MAR","ZCH27",-14),
        ],
    },
    {
        "timestamp": "2026-05-20T20:43:39.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCN26",-21),
            row("CN_MAY","Corn","MAY","ZCN26",-21),
            row("CN_JUN","Corn","JUN","ZCN26",-18),
            row("CN_JUL","Corn","JUL","ZCN26",-15),
            row("CN_AUG","Corn","AUG","ZCU26",-15),
            row("CN_SEP","Corn","SEP","ZCU26",-15),
            row("CN_OCT","Corn","OCT","ZCZ26",-24),
            row("CN_NOV","Corn","NOV","ZCZ26",-22),
            row("CN_DEC","Corn","DEC","ZCZ26",-15),
            row("CN_JAN","Corn","JAN","ZCH27",-18),
            row("CN_FEB","Corn","FEB","ZCH27",-16),
            row("CN_MAR","Corn","MAR","ZCH27",-14),
        ],
    },
    {
        "timestamp": "2026-05-21T20:45:51.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCN26",-21),
            row("CN_MAY","Corn","MAY","ZCN26",-21),
            row("CN_JUN","Corn","JUN","ZCN26",-18),
            row("CN_JUL","Corn","JUL","ZCN26",-15),
            row("CN_AUG","Corn","AUG","ZCU26",-15),
            row("CN_SEP","Corn","SEP","ZCU26",-15),
            row("CN_OCT","Corn","OCT","ZCZ26",-24),
            row("CN_NOV","Corn","NOV","ZCZ26",-22),
            row("CN_DEC","Corn","DEC","ZCZ26",-15),
            row("CN_JAN","Corn","JAN","ZCH27",-18),
            row("CN_FEB","Corn","FEB","ZCH27",-16),
            row("CN_MAR","Corn","MAR","ZCH27",-14),
        ],
    },
    {
        "timestamp": "2026-05-22T20:43:46.000Z", "provider": "ADM", "location": "ADM Cedar Rapids",
        "rows": [
            spot("Corn","MAY","ZCN26",-21),
            row("CN_MAY","Corn","MAY","ZCN26",-21),
            row("CN_JUN","Corn","JUN","ZCN26",-18),
            row("CN_JUL","Corn","JUL","ZCN26",-15),
            row("CN_AUG","Corn","AUG","ZCU26",-15),
            row("CN_SEP","Corn","SEP","ZCU26",-15),
            row("CN_OCT","Corn","OCT","ZCZ26",-24),
            row("CN_NOV","Corn","NOV","ZCZ26",-22),
            row("CN_DEC","Corn","DEC","ZCZ26",-15),
            row("CN_JAN","Corn","JAN","ZCH27",-18),
            row("CN_FEB","Corn","FEB","ZCH27",-16),
            row("CN_MAR","Corn","MAR","ZCH27",-14),
        ],
    },
]

# ── ADM St. Louis ─────────────────────────────────────────────────────────────
ADM_ST_LOUIS = [
    {
        "timestamp": "2025-05-23T19:39:22.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCN25",21),
            row("WH_MAY","Wheat","MAY","ZWN25",-5),
            row("WH_JUL","Wheat","JUL","ZWN25",0),
            row("WH_AUG","Wheat","AUG","ZWU25",-25),
            row("WH_SEP","Wheat","SEP","ZWU25",-47),
            row("WH_OCT","Wheat","OCT","ZWZ25",-25),
            row("WH_NOV","Wheat","NOV","ZWZ25",-25),
            row("WH_DEC","Wheat","DEC","ZWZ25",0),
            row("WH_JAN","Wheat","JAN","ZWH26",1),
            row("WH_FEB","Wheat","FEB","ZWH26",1),
            row("WH_MAR","Wheat","MAR","ZWH26",1),
            row("SB_MAY","Soybeans","MAY","ZSN25",13),
            row("SB_JUN","Soybeans","JUN","ZSN25",19),
            row("SB_JUL","Soybeans","JUL","ZSN25",22),
            row("SB_AUG","Soybeans","AUG","ZSQ25",8),
            row("SB_SEP","Soybeans","SEP","ZSX25",-6),
            row("SB_NOV","Soybeans","NOV","ZSX25",5),
            row("SB_DEC","Soybeans","DEC","ZSF26",6),
            row("SB_JAN","Soybeans","JAN","ZSF26",5),
            row("SB_FEB","Soybeans","FEB","ZSH26",5),
            row("SB_MAR","Soybeans","MAR","ZSH26",5),
            row("CN_MAY","Corn","MAY","ZCN25",21),
            row("CN_JUN","Corn","JUN","ZCN25",23),
            row("CN_JUL","Corn","JUL","ZCN25",24),
            row("CN_AUG","Corn","AUG","ZCU25",8),
            row("CN_SEP","Corn","SEP","ZCU25",-5),
            row("CN_OCT","Corn","OCT","ZCZ25",-8),
            row("CN_NOV","Corn","NOV","ZCZ25",5),
            row("CN_DEC","Corn","DEC","ZCZ25",8),
            row("CN_JAN","Corn","JAN","ZCH26",1),
            row("CN_FEB","Corn","FEB","ZCH26",3),
            row("CN_MAR","Corn","MAR","ZCH26",4),
        ],
    },
    {
        "timestamp": "2026-04-24T20:44:30.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCK26",37),
            row("WH_APR","Wheat","APR","ZWK26",5),
            row("WH_MAY","Wheat","MAY","ZWK26",7),
            row("WH_NC26","Wheat","N/C 26","ZWN26",-5),
            row("WH_AUG","Wheat","AUG","ZWU26",-17),
            row("WH_SEP","Wheat","SEP","ZWU26",-25),
            row("WH_NOV","Wheat","NOV","ZWZ26",-29),
            row("WH_DEC","Wheat","DEC","ZWZ26",-3),
            row("WH_JAN","Wheat","JAN","ZWH27",-10),
            row("SB_APR","Soybeans","APR","ZSK26",33),
            row("SB_MAY","Soybeans","MAY","ZSK26",36),
            row("SB_JUN","Soybeans","JUN","ZSN26",22),
            row("SB_JUL","Soybeans","JUL","ZSN26",26),
            row("SB_AUG","Soybeans","AUG","ZSQ26",11),
            row("SB_SEP","Soybeans","SEP","ZSX26",-11),
            row("SB_NC26","Soybeans","N/C 26","ZSX26",-12),
            row("SB_NOV","Soybeans","NOV","ZSX26",3),
            row("SB_DEC","Soybeans","DEC","ZSF27",5),
            row("SB_JAN","Soybeans","JAN","ZSF27",7),
            row("SB_FEB","Soybeans","FEB","ZSH27",20),
            row("SB_MAR","Soybeans","MAR","ZSH27",22),
            row("CN_APR","Corn","APR","ZCK26",40),
            row("CN_MAY","Corn","MAY","ZCK26",37),
            row("CN_JUN","Corn","JUN","ZCN26",28),
            row("CN_JUL","Corn","JUL","ZCN26",29),
            row("CN_AUG","Corn","AUG","ZCU26",11),
            row("CN_SEP","Corn","SEP","ZCU26",0),
            row("CN_NC26","Corn","N/C 26","ZCZ26",-13),
            row("CN_NOV","Corn","NOV","ZCZ26",0),
            row("CN_DEC","Corn","DEC","ZCZ26",14),
            row("CN_JAN","Corn","JAN","ZCH27",7),
            row("CN_FEB","Corn","FEB","ZCH27",19),
            row("CN_MAR","Corn","MAR","ZCH27",21),
        ],
    },
    {
        "timestamp": "2026-05-14T20:44:30.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCN26",18),
            row("WH_MAY","Wheat","MAY","ZWN26",-7),
            row("WH_NC26","Wheat","N/C 26","ZWN26",-13),
            row("WH_AUG","Wheat","AUG","ZWU26",-22),
            row("WH_SEP","Wheat","SEP","ZWU26",-25),
            row("WH_NOV","Wheat","NOV","ZWZ26",-29),
            row("WH_DEC","Wheat","DEC","ZWZ26",-3),
            row("WH_JAN","Wheat","JAN","ZWH27",-10),
            row("WH_JUL27","Wheat","JUL '27","ZWN27",-50),
            row("SB_MAY","Soybeans","MAY","ZSN26",18),
            row("SB_JUN","Soybeans","JUN","ZSN26",21),
            row("SB_JUL","Soybeans","JUL","ZSN26",25),
            row("SB_AUG","Soybeans","AUG","ZSQ26",8),
            row("SB_SEP","Soybeans","SEP","ZSX26",-15),
            row("SB_NC26","Soybeans","N/C 26","ZSX26",-15),
            row("SB_NOV","Soybeans","NOV","ZSX26",5),
            row("SB_DEC","Soybeans","DEC","ZSF27",8),
            row("SB_JAN","Soybeans","JAN","ZSF27",13),
            row("SB_FEB","Soybeans","FEB","ZSH27",18),
            row("SB_MAR","Soybeans","MAR","ZSH27",20),
            row("CN_MAY","Corn","MAY","ZCN26",18),
            row("CN_JUN","Corn","JUN","ZCN26",24),
            row("CN_JUL","Corn","JUL","ZCN26",28),
            row("CN_AUG","Corn","AUG","ZCU26",12),
            row("CN_SEP","Corn","SEP","ZCU26",0),
            row("CN_NC26","Corn","N/C 26","ZCZ26",-15),
            row("CN_NOV","Corn","NOV","ZCZ26",-2),
            row("CN_DEC","Corn","DEC","ZCZ26",12),
            row("CN_JAN","Corn","JAN","ZCH27",3),
            row("CN_FEB","Corn","FEB","ZCH27",12),
            row("CN_MAR","Corn","MAR","ZCH27",18),
        ],
    },
    {
        "timestamp": "2026-05-20T20:43:39.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCN26",20),
            row("WH_MAY","Wheat","MAY","ZWN26",-5),
            row("WH_NC26","Wheat","N/C 26","ZWN26",-13),
            row("WH_AUG","Wheat","AUG","ZWU26",-22),
            row("WH_SEP","Wheat","SEP","ZWU26",-25),
            row("WH_NOV","Wheat","NOV","ZWZ26",-29),
            row("WH_DEC","Wheat","DEC","ZWZ26",-3),
            row("WH_JAN","Wheat","JAN","ZWH27",-10),
            row("WH_JUL27","Wheat","JUL '27","ZWN27",-50),
            row("SB_MAY","Soybeans","MAY","ZSN26",20),
            row("SB_JUN","Soybeans","JUN","ZSN26",23),
            row("SB_JUL","Soybeans","JUL","ZSN26",27),
            row("SB_AUG","Soybeans","AUG","ZSQ26",10),
            row("SB_SEP","Soybeans","SEP","ZSX26",-14),
            row("SB_NC26","Soybeans","N/C 26","ZSX26",-14),
            row("SB_NOV","Soybeans","NOV","ZSX26",8),
            row("SB_DEC","Soybeans","DEC","ZSF27",11),
            row("SB_JAN","Soybeans","JAN","ZSF27",16),
            row("SB_FEB","Soybeans","FEB","ZSH27",20),
            row("SB_MAR","Soybeans","MAR","ZSH27",23),
            row("CN_MAY","Corn","MAY","ZCN26",20),
            row("CN_JUN","Corn","JUN","ZCN26",26),
            row("CN_JUL","Corn","JUL","ZCN26",30),
            row("CN_AUG","Corn","AUG","ZCU26",15),
            row("CN_SEP","Corn","SEP","ZCU26",3),
            row("CN_NC26","Corn","N/C 26","ZCZ26",-16),
            row("CN_NOV","Corn","NOV","ZCZ26",-3),
            row("CN_DEC","Corn","DEC","ZCZ26",14),
            row("CN_JAN","Corn","JAN","ZCH27",5),
            row("CN_FEB","Corn","FEB","ZCH27",14),
            row("CN_MAR","Corn","MAR","ZCH27",20),
        ],
    },
    {
        "timestamp": "2026-05-21T19:42:28.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCN26",20),
            row("WH_MAY","Wheat","MAY","ZWN26",-5),
            row("WH_NC26","Wheat","N/C 26","ZWN26",-13),
            row("WH_AUG","Wheat","AUG","ZWU26",-22),
            row("WH_SEP","Wheat","SEP","ZWU26",-25),
            row("WH_NOV","Wheat","NOV","ZWZ26",-29),
            row("WH_DEC","Wheat","DEC","ZWZ26",-3),
            row("WH_JAN","Wheat","JAN","ZWH27",-10),
            row("WH_JUL27","Wheat","JUL '27","ZWN27",-50),
            row("SB_MAY","Soybeans","MAY","ZSN26",20),
            row("SB_JUN","Soybeans","JUN","ZSN26",23),
            row("SB_JUL","Soybeans","JUL","ZSN26",27),
            row("SB_AUG","Soybeans","AUG","ZSQ26",10),
            row("SB_SEP","Soybeans","SEP","ZSX26",-14),
            row("SB_NC26","Soybeans","N/C 26","ZSX26",-14),
            row("SB_NOV","Soybeans","NOV","ZSX26",8),
            row("SB_DEC","Soybeans","DEC","ZSF27",11),
            row("SB_JAN","Soybeans","JAN","ZSF27",16),
            row("SB_FEB","Soybeans","FEB","ZSH27",20),
            row("SB_MAR","Soybeans","MAR","ZSH27",23),
            row("CN_MAY","Corn","MAY","ZCN26",20),
            row("CN_JUN","Corn","JUN","ZCN26",26),
            row("CN_JUL","Corn","JUL","ZCN26",30),
            row("CN_AUG","Corn","AUG","ZCU26",15),
            row("CN_SEP","Corn","SEP","ZCU26",3),
            row("CN_NC26","Corn","N/C 26","ZCZ26",-16),
            row("CN_NOV","Corn","NOV","ZCZ26",-3),
            row("CN_DEC","Corn","DEC","ZCZ26",14),
            row("CN_JAN","Corn","JAN","ZCH27",5),
            row("CN_FEB","Corn","FEB","ZCH27",14),
            row("CN_MAR","Corn","MAR","ZCH27",20),
        ],
    },
    {
        "timestamp": "2026-05-22T20:43:46.000Z", "provider": "ADM", "location": "ADM St. Louis",
        "rows": [
            spot("Corn","MAY","ZCN26",21),
            row("WH_MAY","Wheat","MAY","ZWN26",-5),
            row("WH_NC26","Wheat","N/C 26","ZWN26",-11),
            row("WH_AUG","Wheat","AUG","ZWU26",-22),
            row("WH_SEP","Wheat","SEP","ZWU26",-25),
            row("WH_NOV","Wheat","NOV","ZWZ26",-29),
            row("WH_DEC","Wheat","DEC","ZWZ26",-3),
            row("WH_JAN","Wheat","JAN","ZWH27",-10),
            row("WH_JUL27","Wheat","JUL '27","ZWN27",-50),
            row("SB_MAY","Soybeans","MAY","ZSN26",21),
            row("SB_JUN","Soybeans","JUN","ZSN26",24),
            row("SB_JUL","Soybeans","JUL","ZSN26",29),
            row("SB_AUG","Soybeans","AUG","ZSQ26",10),
            row("SB_SEP","Soybeans","SEP","ZSX26",-14),
            row("SB_NC26","Soybeans","N/C 26","ZSX26",-14),
            row("SB_NOV","Soybeans","NOV","ZSX26",8),
            row("SB_DEC","Soybeans","DEC","ZSF27",11),
            row("SB_JAN","Soybeans","JAN","ZSF27",16),
            row("SB_FEB","Soybeans","FEB","ZSH27",20),
            row("SB_MAR","Soybeans","MAR","ZSH27",23),
            row("CN_MAY","Corn","MAY","ZCN26",21),
            row("CN_JUN","Corn","JUN","ZCN26",26),
            row("CN_JUL","Corn","JUL","ZCN26",31),
            row("CN_AUG","Corn","AUG","ZCU26",15),
            row("CN_SEP","Corn","SEP","ZCU26",3),
            row("CN_NC26","Corn","N/C 26","ZCZ26",-16),
            row("CN_NOV","Corn","NOV","ZCZ26",-3),
            row("CN_DEC","Corn","DEC","ZCZ26",14),
            row("CN_JAN","Corn","JAN","ZCH27",5),
            row("CN_FEB","Corn","FEB","ZCH27",14),
            row("CN_MAR","Corn","MAR","ZCH27",20),
        ],
    },
]

# ── Mendota helper to build a full timestamp block ────────────────────────────
def mendota_snap(ts, loc, spots_dict, rows_list):
    spot_rows = [
        spot(g, s["dm"], s["sym"], s["basis"])
        for g, s in spots_dict.items()
    ]
    return {"timestamp": ts, "provider": "Mendota", "location": loc,
            "rows": spot_rows + rows_list}

# ── Mendota 2025-05-30 ────────────────────────────────────────────────────────
M_2025_05_30 = "2025-05-30T20:18:58.000Z"
MENDOTA_2025_05_30 = [
    mendota_snap(M_2025_05_30, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCN25","basis":2}, "Soybeans":{"dm":"MAY","sym":"ZSN25","basis":-10}},
        [row("CN_MAY","Corn","MAY","ZCN25",2), row("CN_JUN","Corn","JUN","ZCN25",3),
         row("CN_JUL","Corn","JUL","ZCN25",4), row("CN_OCT","Corn","OCT/NOV","ZCZ25",-35),
         row("CN_DEC","Corn","DEC","ZCZ25",-5),
         row("SB_MAY","Soybeans","MAY","ZSN25",-10), row("SB_JUN","Soybeans","JUN","ZSN25",-4),
         row("SB_JUL","Soybeans","JUL","ZSN25",0), row("SB_OCT","Soybeans","OCT/NOV","ZSX25",-35),
         row("SB_DEC","Soybeans","DEC","ZSF26",-14), row("SB_JAN","Soybeans","JAN","ZSF26",-5)]),
    mendota_snap(M_2025_05_30, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCN25","basis":0}, "Soybeans":{"dm":"MAY","sym":"ZSN25","basis":-18}},
        [row("CN_MAY","Corn","MAY","ZCN25",0), row("CN_JUN","Corn","JUN","ZCN25",-3),
         row("CN_JUL","Corn","JUL","ZCN25",-3), row("CN_OCT","Corn","OCT/NOV","ZCZ25",-20),
         row("CN_DEC","Corn","DEC","ZCZ25",-20),
         row("SB_MAY","Soybeans","MAY","ZSN25",-18), row("SB_JUN","Soybeans","JUN","ZSN25",-13),
         row("SB_JUL","Soybeans","JUL","ZSN25",-7), row("SB_OCT","Soybeans","OCT/NOV","ZSX25",-45),
         row("SB_DEC","Soybeans","DEC","ZSF26",-25)]),
    mendota_snap(M_2025_05_30, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCN25","basis":7}},
        [row("CN_MAY","Corn","MAY","ZCN25",7), row("CN_JUN","Corn","JUN","ZCN25",8),
         row("CN_JUL","Corn","JUL","ZCN25",9), row("CN_OCT","Corn","OCT/NOV","ZCZ25",-30),
         row("CN_DEC","Corn","DEC","ZCZ25",0)]),
    mendota_snap(M_2025_05_30, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCN25","basis":-5}},
        [row("CN_MAY","Corn","MAY","ZCN25",-5), row("CN_JUN","Corn","JUN","ZCN25",-5),
         row("CN_JUL","Corn","JUL","ZCN25",-3), row("CN_OCT","Corn","OCT/NOV","ZCZ25",-40),
         row("CN_DEC","Corn","DEC","ZCZ25",-20)]),
    mendota_snap(M_2025_05_30, "Mendota Mill",
        {"Wheat":{"dm":"MAY","sym":"ZWN25","basis":-35}},
        [row("WH_MAY","Wheat","MAY","ZWN25",-35), row("WH_JUN","Wheat","JUN","ZWN25",-20),
         row("WH_JUL","Wheat","JUL","ZWN25",-5), row("WH_AUG","Wheat","AUG","ZWU25",-5),
         row("WH_SEP","Wheat","SEP","ZWU25",0), row("WH_OCT","Wheat","OCT","ZWZ25",-5),
         row("WH_DEC","Wheat","DEC","ZWZ25",5), row("WH_JAN","Wheat","JAN","ZWH26",0)]),
    mendota_snap(M_2025_05_30, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCN25","basis":-10}},
        [row("CN_MAY","Corn","MAY","ZCN25",-10), row("CN_JUN","Corn","JUN","ZCN25",-10),
         row("CN_JUL","Corn","JUL","ZCN25",-10), row("CN_OCT","Corn","OCT/NOV","ZCZ25",-30),
         row("CN_DEC","Corn","DEC","ZCZ25",-15)]),
]

# ── Mendota 2026-04-24 ────────────────────────────────────────────────────────
M_2026_04_24 = "2026-04-24T20:22:56.000Z"
MENDOTA_2026_04_24 = [
    mendota_snap(M_2026_04_24, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCK26","basis":5}, "Soybeans":{"dm":"MAY","sym":"ZSK26","basis":-2}},
        [row("CN_LH_APR","Corn","LH APR","ZCK26",4), row("CN_MAY","Corn","MAY","ZCK26",5),
         row("CN_JUN","Corn","JUN","ZCN26",-1), row("CN_JUL","Corn","JUL","ZCN26",0),
         row("CN_AUG","Corn","AUG","ZCU26",-10), row("CN_SEP","Corn","SEP","ZCU26",-23),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-30), row("CN_DEC","Corn","DEC","ZCZ26",-8),
         row("CN_JAN","Corn","JAN","ZCH27",-15),
         row("SB_LH_APR","Soybeans","LH APR","ZSK26",-5), row("SB_MAY","Soybeans","MAY","ZSK26",-2),
         row("SB_JUN","Soybeans","JUN","ZSN26",-14), row("SB_JUL","Soybeans","JUL","ZSN26",-5),
         row("SB_AUG","Soybeans","AUG","ZSQ26",-15), row("SB_SEP","Soybeans","SEP","ZSX26",-38),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-38), row("SB_DEC","Soybeans","DEC","ZSF27",-30),
         row("SB_JAN","Soybeans","JAN","ZSF27",-15)]),
    mendota_snap(M_2026_04_24, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCK26","basis":11}, "Soybeans":{"dm":"MAY","sym":"ZSK26","basis":5}},
        [row("CN_LH_APR","Corn","LH APR","ZCK26",11), row("CN_MAY","Corn","MAY","ZCK26",11),
         row("CN_JUN","Corn","JUN","ZCN26",7), row("CN_JUL","Corn","JUL","ZCN26",6),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-25), row("CN_DEC","Corn","DEC","ZCZ26",-5),
         row("CN_JAN","Corn","JAN","ZCH27",-8),
         row("SB_LH_APR","Soybeans","LH APR","ZSK26",0), row("SB_MAY","Soybeans","MAY","ZSK26",5),
         row("SB_JUN","Soybeans","JUN","ZSN26",-7), row("SB_JUL","Soybeans","JUL","ZSN26",0),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-30), row("SB_DEC","Soybeans","DEC","ZSF27",-10),
         row("SB_JAN","Soybeans","JAN","ZSF27",-10)]),
    mendota_snap(M_2026_04_24, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCK26","basis":0}, "Soybeans":{"dm":"MAY","sym":"ZSK26","basis":-7}},
        [row("CN_LH_APR","Corn","LH APR","ZCK26",-2), row("CN_MAY","Corn","MAY","ZCK26",0),
         row("CN_JUN","Corn","JUN","ZCN26",-6), row("CN_JUL","Corn","JUL","ZCN26",-5),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-20),
         row("CN_JAN","Corn","JAN","ZCH27",-20),
         row("SB_LH_APR","Soybeans","LH APR","ZSK26",-15), row("SB_MAY","Soybeans","MAY","ZSK26",-7),
         row("SB_JUN","Soybeans","JUN","ZSN26",-19), row("SB_JUL","Soybeans","JUL","ZSN26",-15),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-44), row("SB_DEC","Soybeans","DEC","ZSF27",-30)]),
    mendota_snap(M_2026_04_24, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCK26","basis":-5}},
        [row("CN_LH_APR","Corn","LH APR","ZCK26",-7), row("CN_MAY","Corn","MAY","ZCK26",-5),
         row("CN_JUN","Corn","JUN","ZCN26",-11), row("CN_JUL","Corn","JUL","ZCN26",-8),
         row("CN_AUG","Corn","AUG","ZCU26",-14), row("CN_SEP","Corn","SEP","ZCU26",-14),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-29), row("CN_DEC","Corn","DEC","ZCZ26",-17)]),
    mendota_snap(M_2026_04_24, "Mendota Mill",
        {"Wheat":{"dm":"LH APR","sym":"ZWK26","basis":-55}},
        [row("WH_LH_APR","Wheat","LH APR","ZWK26",-55), row("WH_FH_MAY","Wheat","FH MAY","ZWK26",-40),
         row("WH_LH_MAY","Wheat","LH MAY","ZWK26",-40), row("WH_FH_JUN","Wheat","FH JUN","ZWN26",-45),
         row("WH_LH_JUN","Wheat","LH JUN","ZWN26",-15), row("WH_JUL","Wheat","JUL","ZWN26",-5),
         row("WH_AUG","Wheat","AUG","ZWU26",-15), row("WH_SEP","Wheat","SEP","ZWU26",-10),
         row("WH_OCT","Wheat","OCT/NOV","ZWZ26",-10), row("WH_DEC","Wheat","DEC","ZWZ26",0)]),
    mendota_snap(M_2026_04_24, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCK26","basis":-13}},
        [row("CN_LH_APR","Corn","LH APR","ZCK26",-13), row("CN_MAY","Corn","MAY","ZCK26",-13),
         row("CN_JUN","Corn","JUN","ZCN26",-16), row("CN_JUL","Corn","JUL","ZCN26",-16),
         row("CN_AUG","Corn","AUG","ZCU26",-25), row("CN_SEP","Corn","SEP","ZCU26",-35),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-25),
         row("CN_JAN","Corn","JAN","ZCH27",-32)]),
]

# ── Mendota 2026-05-15 ────────────────────────────────────────────────────────
M_2026_05_15 = "2026-05-15T20:31:23.000Z"
MENDOTA_2026_05_15 = [
    mendota_snap(M_2026_05_15, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-10}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-15}},
        [row("CN_MAY","Corn","MAY","ZCN26",-10), row("CN_JUN","Corn","JUN","ZCN26",-3),
         row("CN_JUL","Corn","JUL","ZCN26",-2), row("CN_AUG","Corn","AUG","ZCU26",-12),
         row("CN_SEP","Corn","SEP","ZCU26",-23), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-30),
         row("CN_DEC","Corn","DEC","ZCZ26",-8), row("CN_JAN","Corn","JAN","ZCH27",-15),
         row("SB_MAY","Soybeans","MAY","ZSN26",-15), row("SB_JUN","Soybeans","JUN","ZSN26",-12),
         row("SB_JUL","Soybeans","JUL","ZSN26",-6), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_SEP","Soybeans","SEP","ZSX26",-38), row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-38),
         row("SB_DEC","Soybeans","DEC","ZSF27",-30), row("SB_JAN","Soybeans","JAN","ZSF27",-15)]),
    mendota_snap(M_2026_05_15, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-3}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-8}},
        [row("CN_MAY","Corn","MAY","ZCN26",-3), row("CN_JUN","Corn","JUN","ZCN26",4),
         row("CN_JUL","Corn","JUL","ZCN26",6), row("CN_AUG","Corn","AUG","ZCU26",-1),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-25), row("CN_DEC","Corn","DEC","ZCZ26",-5),
         row("CN_JAN","Corn","JAN","ZCH27",-8),
         row("SB_MAY","Soybeans","MAY","ZSN26",-8), row("SB_JUN","Soybeans","JUN","ZSN26",-2),
         row("SB_JUL","Soybeans","JUL","ZSN26",2), row("SB_AUG","Soybeans","AUG","ZSQ26",-10),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-30), row("SB_DEC","Soybeans","DEC","ZSF27",-10),
         row("SB_JAN","Soybeans","JAN","ZSF27",-10)]),
    mendota_snap(M_2026_05_15, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-12}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-20}},
        [row("CN_MAY","Corn","MAY","ZCN26",-12), row("CN_JUN","Corn","JUN","ZCN26",-9),
         row("CN_JUL","Corn","JUL","ZCN26",-5), row("CN_AUG","Corn","AUG","ZCU26",-15),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-20),
         row("CN_JAN","Corn","JAN","ZCH27",-20),
         row("SB_MAY","Soybeans","MAY","ZSN26",-20), row("SB_JUN","Soybeans","JUN","ZSN26",-15),
         row("SB_JUL","Soybeans","JUL","ZSN26",-8), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-44), row("SB_DEC","Soybeans","DEC","ZSF27",-30)]),
    mendota_snap(M_2026_05_15, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-15}},
        [row("CN_MAY","Corn","MAY","ZCN26",-15), row("CN_JUN","Corn","JUN","ZCN26",-12),
         row("CN_JUL","Corn","JUL","ZCN26",-12), row("CN_AUG","Corn","AUG","ZCU26",-17),
         row("CN_SEP","Corn","SEP","ZCU26",-17), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-26),
         row("CN_DEC","Corn","DEC","ZCZ26",-17)]),
    mendota_snap(M_2026_05_15, "Mendota Mill",
        {"Wheat":{"dm":"FH MAY","sym":"ZWN26","basis":-55}},
        [row("WH_FH_MAY","Wheat","FH MAY","ZWN26",-55), row("WH_LH_MAY","Wheat","LH MAY","ZWN26",-55),
         row("WH_FH_JUN","Wheat","FH JUN","ZWN26",-45), row("WH_LH_JUN","Wheat","LH JUN","ZWN26",-15),
         row("WH_JUL","Wheat","JUL","ZWN26",-5), row("WH_AUG","Wheat","AUG","ZWU26",-15),
         row("WH_SEP","Wheat","SEP","ZWU26",-10), row("WH_OCT","Wheat","OCT/NOV","ZWZ26",-10),
         row("WH_DEC","Wheat","DEC","ZWZ26",0), row("WH_JAN","Wheat","JAN","ZWH27",-10)]),
    mendota_snap(M_2026_05_15, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-22}},
        [row("CN_MAY","Corn","MAY","ZCN26",-22), row("CN_JUN","Corn","JUN","ZCN26",-20),
         row("CN_JUL","Corn","JUL","ZCN26",-18), row("CN_AUG","Corn","AUG","ZCU26",-18),
         row("CN_SEP","Corn","SEP","ZCU26",-35), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35),
         row("CN_DEC","Corn","DEC","ZCZ26",-25), row("CN_JAN","Corn","JAN","ZCH27",-32)]),
]

# ── Mendota 2026-05-20 ────────────────────────────────────────────────────────
M_2026_05_20 = "2026-05-20T20:33:21.000Z"
MENDOTA_2026_05_20 = [
    mendota_snap(M_2026_05_20, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-10}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-15}},
        [row("CN_MAY","Corn","MAY","ZCN26",-10), row("CN_JUN","Corn","JUN","ZCN26",-2),
         row("CN_JUL","Corn","JUL","ZCN26",-1), row("CN_AUG","Corn","AUG","ZCU26",-12),
         row("CN_SEP","Corn","SEP","ZCU26",-23), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-30),
         row("CN_DEC","Corn","DEC","ZCZ26",-8), row("CN_JAN","Corn","JAN","ZCH27",-15),
         row("SB_MAY","Soybeans","MAY","ZSN26",-15), row("SB_JUN","Soybeans","JUN","ZSN26",-9),
         row("SB_JUL","Soybeans","JUL","ZSN26",-3), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_SEP","Soybeans","SEP","ZSX26",-38), row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-38),
         row("SB_DEC","Soybeans","DEC","ZSF27",-30), row("SB_JAN","Soybeans","JAN","ZSF27",-15)]),
    mendota_snap(M_2026_05_20, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-2}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-8}},
        [row("CN_MAY","Corn","MAY","ZCN26",-2), row("CN_JUN","Corn","JUN","ZCN26",4),
         row("CN_JUL","Corn","JUL","ZCN26",7), row("CN_AUG","Corn","AUG","ZCU26",-1),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-25), row("CN_DEC","Corn","DEC","ZCZ26",-5),
         row("CN_JAN","Corn","JAN","ZCH27",-8),
         row("SB_MAY","Soybeans","MAY","ZSN26",-8), row("SB_JUN","Soybeans","JUN","ZSN26",-2),
         row("SB_JUL","Soybeans","JUL","ZSN26",3), row("SB_AUG","Soybeans","AUG","ZSQ26",-10),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-30), row("SB_DEC","Soybeans","DEC","ZSF27",-10),
         row("SB_JAN","Soybeans","JAN","ZSF27",-10)]),
    mendota_snap(M_2026_05_20, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-12}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-20}},
        [row("CN_MAY","Corn","MAY","ZCN26",-12), row("CN_JUN","Corn","JUN","ZCN26",-7),
         row("CN_JUL","Corn","JUL","ZCN26",-3), row("CN_AUG","Corn","AUG","ZCU26",-15),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-20),
         row("CN_JAN","Corn","JAN","ZCH27",-20),
         row("SB_MAY","Soybeans","MAY","ZSN26",-20), row("SB_JUN","Soybeans","JUN","ZSN26",-14),
         row("SB_JUL","Soybeans","JUL","ZSN26",-7), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-44), row("SB_DEC","Soybeans","DEC","ZSF27",-30)]),
    mendota_snap(M_2026_05_20, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-14}},
        [row("CN_MAY","Corn","MAY","ZCN26",-14), row("CN_JUN","Corn","JUN","ZCN26",-12),
         row("CN_JUL","Corn","JUL","ZCN26",-12), row("CN_AUG","Corn","AUG","ZCU26",-17),
         row("CN_SEP","Corn","SEP","ZCU26",-17), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-26),
         row("CN_DEC","Corn","DEC","ZCZ26",-17)]),
    mendota_snap(M_2026_05_20, "Mendota Mill",
        {"Wheat":{"dm":"LH MAY","sym":"ZWN26","basis":-55}},
        [row("WH_LH_MAY","Wheat","LH MAY","ZWN26",-55), row("WH_FH_JUN","Wheat","FH JUN","ZWN26",-45),
         row("WH_LH_JUN","Wheat","LH JUN","ZWN26",-15), row("WH_JUL","Wheat","JUL","ZWN26",-5),
         row("WH_AUG","Wheat","AUG","ZWU26",-15), row("WH_SEP","Wheat","SEP","ZWU26",-10),
         row("WH_OCT","Wheat","OCT/NOV","ZWZ26",-10), row("WH_DEC","Wheat","DEC","ZWZ26",0),
         row("WH_JAN","Wheat","JAN","ZWH27",-10), row("WH_FEB","Wheat","FEB","ZWH27",-5),
         row("WH_MAR","Wheat","MAR","ZWH27",0), row("WH_JUL27","Wheat","JUL 27","ZWN27",-20),
         row("WH_AUG27","Wheat","AUG 27","ZWQ27",-20), row("WH_SEP27","Wheat","SEP 27","ZWU27",-15)]),
    mendota_snap(M_2026_05_20, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-22}},
        [row("CN_MAY","Corn","MAY","ZCN26",-22), row("CN_JUN","Corn","JUN","ZCN26",-20),
         row("CN_JUL","Corn","JUL","ZCN26",-18), row("CN_AUG","Corn","AUG","ZCU26",-18),
         row("CN_SEP","Corn","SEP","ZCU26",-35), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35),
         row("CN_DEC","Corn","DEC","ZCZ26",-20), row("CN_JAN","Corn","JAN","ZCH27",-30)]),
]

# ── Mendota 2026-05-21 ────────────────────────────────────────────────────────
M_2026_05_21 = "2026-05-21T20:25:11.000Z"
MENDOTA_2026_05_21 = [
    mendota_snap(M_2026_05_21, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-10}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-15}},
        [row("CN_MAY","Corn","MAY","ZCN26",-10), row("CN_JUN","Corn","JUN","ZCN26",-2),
         row("CN_JUL","Corn","JUL","ZCN26",-1), row("CN_AUG","Corn","AUG","ZCU26",-12),
         row("CN_SEP","Corn","SEP","ZCU26",-23), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-30),
         row("CN_DEC","Corn","DEC","ZCZ26",-8), row("CN_JAN","Corn","JAN","ZCH27",-15),
         row("SB_MAY","Soybeans","MAY","ZSN26",-15), row("SB_JUN","Soybeans","JUN","ZSN26",-9),
         row("SB_JUL","Soybeans","JUL","ZSN26",-3), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_SEP","Soybeans","SEP","ZSX26",-38), row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-38),
         row("SB_DEC","Soybeans","DEC","ZSF27",-30), row("SB_JAN","Soybeans","JAN","ZSF27",-15)]),
    mendota_snap(M_2026_05_21, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-2}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-8}},
        [row("CN_MAY","Corn","MAY","ZCN26",-2), row("CN_JUN","Corn","JUN","ZCN26",4),
         row("CN_JUL","Corn","JUL","ZCN26",7), row("CN_AUG","Corn","AUG","ZCU26",-1),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-25), row("CN_DEC","Corn","DEC","ZCZ26",-5),
         row("CN_JAN","Corn","JAN","ZCH27",-8),
         row("SB_MAY","Soybeans","MAY","ZSN26",-8), row("SB_JUN","Soybeans","JUN","ZSN26",-2),
         row("SB_JUL","Soybeans","JUL","ZSN26",3), row("SB_AUG","Soybeans","AUG","ZSQ26",-10),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-30), row("SB_DEC","Soybeans","DEC","ZSF27",-10),
         row("SB_JAN","Soybeans","JAN","ZSF27",-10)]),
    mendota_snap(M_2026_05_21, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-12}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-20}},
        [row("CN_MAY","Corn","MAY","ZCN26",-12), row("CN_JUN","Corn","JUN","ZCN26",-7),
         row("CN_JUL","Corn","JUL","ZCN26",-3), row("CN_AUG","Corn","AUG","ZCU26",-15),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-20),
         row("CN_JAN","Corn","JAN","ZCH27",-20),
         row("SB_MAY","Soybeans","MAY","ZSN26",-20), row("SB_JUN","Soybeans","JUN","ZSN26",-14),
         row("SB_JUL","Soybeans","JUL","ZSN26",-7), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-44), row("SB_DEC","Soybeans","DEC","ZSF27",-30)]),
    mendota_snap(M_2026_05_21, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-14}},
        [row("CN_MAY","Corn","MAY","ZCN26",-14), row("CN_JUN","Corn","JUN","ZCN26",-12),
         row("CN_JUL","Corn","JUL","ZCN26",-12), row("CN_AUG","Corn","AUG","ZCU26",-17),
         row("CN_SEP","Corn","SEP","ZCU26",-17), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-26),
         row("CN_DEC","Corn","DEC","ZCZ26",-17)]),
    mendota_snap(M_2026_05_21, "Mendota Mill",
        {"Wheat":{"dm":"LH MAY","sym":"ZWN26","basis":-55}},
        [row("WH_LH_MAY","Wheat","LH MAY","ZWN26",-55), row("WH_FH_JUN","Wheat","FH JUN","ZWN26",-45),
         row("WH_LH_JUN","Wheat","LH JUN","ZWN26",-15), row("WH_JUL","Wheat","JUL","ZWN26",-5),
         row("WH_AUG","Wheat","AUG","ZWU26",-15), row("WH_SEP","Wheat","SEP","ZWU26",-10),
         row("WH_OCT","Wheat","OCT/NOV","ZWZ26",-10), row("WH_DEC","Wheat","DEC","ZWZ26",0),
         row("WH_JAN","Wheat","JAN","ZWH27",-10), row("WH_FEB","Wheat","FEB","ZWH27",-5),
         row("WH_MAR","Wheat","MAR","ZWH27",0), row("WH_JUL27","Wheat","JUL 27","ZWN27",-20),
         row("WH_AUG27","Wheat","AUG 27","ZWQ27",-20), row("WH_SEP27","Wheat","SEP 27","ZWU27",-15)]),
    mendota_snap(M_2026_05_21, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-22}},
        [row("CN_MAY","Corn","MAY","ZCN26",-22), row("CN_JUN","Corn","JUN","ZCN26",-20),
         row("CN_JUL","Corn","JUL","ZCN26",-18), row("CN_AUG","Corn","AUG","ZCU26",-18),
         row("CN_SEP","Corn","SEP","ZCU26",-35), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35),
         row("CN_DEC","Corn","DEC","ZCZ26",-20), row("CN_JAN","Corn","JAN","ZCH27",-30)]),
]

# ── Mendota 2026-05-22 ────────────────────────────────────────────────────────
M_2026_05_22 = "2026-05-22T20:30:13.000Z"
MENDOTA_2026_05_22 = [
    mendota_snap(M_2026_05_22, "Ottawa",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-10}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-14}},
        [row("CN_MAY","Corn","MAY","ZCN26",-10), row("CN_JUN","Corn","JUN","ZCN26",-2),
         row("CN_JUL","Corn","JUL","ZCN26",0), row("CN_AUG","Corn","AUG","ZCU26",-10),
         row("CN_SEP","Corn","SEP","ZCU26",-23), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-30),
         row("CN_DEC","Corn","DEC","ZCZ26",-8), row("CN_JAN","Corn","JAN","ZCH27",-15),
         row("SB_MAY","Soybeans","MAY","ZSN26",-14), row("SB_JUN","Soybeans","JUN","ZSN26",-9),
         row("SB_JUL","Soybeans","JUL","ZSN26",-2), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_SEP","Soybeans","SEP","ZSX26",-38), row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-38),
         row("SB_DEC","Soybeans","DEC","ZSF27",-30), row("SB_JAN","Soybeans","JAN","ZSF27",-15)]),
    mendota_snap(M_2026_05_22, "Havana",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-2}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-8}},
        [row("CN_MAY","Corn","MAY","ZCN26",-2), row("CN_JUN","Corn","JUN","ZCN26",4),
         row("CN_JUL","Corn","JUL","ZCN26",7), row("CN_AUG","Corn","AUG","ZCU26",0),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-25), row("CN_DEC","Corn","DEC","ZCZ26",-5),
         row("CN_JAN","Corn","JAN","ZCH27",-8),
         row("SB_MAY","Soybeans","MAY","ZSN26",-8), row("SB_JUN","Soybeans","JUN","ZSN26",-2),
         row("SB_JUL","Soybeans","JUL","ZSN26",3), row("SB_AUG","Soybeans","AUG","ZSQ26",-10),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-30), row("SB_DEC","Soybeans","DEC","ZSF27",-10),
         row("SB_JAN","Soybeans","JAN","ZSF27",-10)]),
    mendota_snap(M_2026_05_22, "Burlington",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-12}, "Soybeans":{"dm":"MAY","sym":"ZSN26","basis":-20}},
        [row("CN_MAY","Corn","MAY","ZCN26",-12), row("CN_JUN","Corn","JUN","ZCN26",-7),
         row("CN_JUL","Corn","JUL","ZCN26",-3), row("CN_AUG","Corn","AUG","ZCU26",-15),
         row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35), row("CN_DEC","Corn","DEC","ZCZ26",-20),
         row("CN_JAN","Corn","JAN","ZCH27",-20),
         row("SB_MAY","Soybeans","MAY","ZSN26",-20), row("SB_JUN","Soybeans","JUN","ZSN26",-15),
         row("SB_JUL","Soybeans","JUL","ZSN26",-7), row("SB_AUG","Soybeans","AUG","ZSQ26",-20),
         row("SB_OCT","Soybeans","OCT/NOV","ZSX26",-44), row("SB_DEC","Soybeans","DEC","ZSF27",-30)]),
    mendota_snap(M_2026_05_22, "Clinton Proc",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-14}},
        [row("CN_MAY","Corn","MAY","ZCN26",-14), row("CN_JUN","Corn","JUN","ZCN26",-12),
         row("CN_JUL","Corn","JUL","ZCN26",-12), row("CN_AUG","Corn","AUG","ZCU26",-17),
         row("CN_SEP","Corn","SEP","ZCU26",-17), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-26),
         row("CN_DEC","Corn","DEC","ZCZ26",-17)]),
    mendota_snap(M_2026_05_22, "Mendota Mill",
        {"Wheat":{"dm":"LH MAY","sym":"ZWN26","basis":-55}},
        [row("WH_LH_MAY","Wheat","LH MAY","ZWN26",-55), row("WH_FH_JUN","Wheat","FH JUN","ZWN26",-45),
         row("WH_LH_JUN","Wheat","LH JUN","ZWN26",-15), row("WH_JUL","Wheat","JUL","ZWN26",-5),
         row("WH_AUG","Wheat","AUG","ZWU26",-15), row("WH_SEP","Wheat","SEP","ZWU26",-10),
         row("WH_OCT","Wheat","OCT/NOV","ZWZ26",-10), row("WH_DEC","Wheat","DEC","ZWZ26",0),
         row("WH_JAN","Wheat","JAN","ZWH27",-10), row("WH_FEB","Wheat","FEB","ZWH27",-5),
         row("WH_MAR","Wheat","MAR","ZWH27",0), row("WH_JUL27","Wheat","JUL 27","ZWN27",-20),
         row("WH_AUG27","Wheat","AUG 27","ZWQ27",-20), row("WH_SEP27","Wheat","SEP 27","ZWU27",-15)]),
    mendota_snap(M_2026_05_22, "Mendota BN Rail",
        {"Corn":{"dm":"MAY","sym":"ZCN26","basis":-22}},
        [row("CN_MAY","Corn","MAY","ZCN26",-22), row("CN_JUN","Corn","JUN","ZCN26",-20),
         row("CN_JUL","Corn","JUL","ZCN26",-18), row("CN_AUG","Corn","AUG","ZCU26",-18),
         row("CN_SEP","Corn","SEP","ZCU26",-35), row("CN_OCT","Corn","OCT/NOV","ZCZ26",-35),
         row("CN_DEC","Corn","DEC","ZCZ26",-20), row("CN_JAN","Corn","JAN","ZCH27",-30)]),
]

# ── All snapshots ─────────────────────────────────────────────────────────────
ALL_SNAPSHOTS = (
    ADM_DECATUR + ADM_CEDAR_RAPIDS + ADM_ST_LOUIS
    + MENDOTA_2025_05_30 + MENDOTA_2026_04_24 + MENDOTA_2026_05_15
    + MENDOTA_2026_05_20 + MENDOTA_2026_05_21 + MENDOTA_2026_05_22
)


def seed_db():
    init_db()
    for snap in ALL_SNAPSHOTS:
        upsert_snapshot(snap)
    print(f"Seeded {len(ALL_SNAPSHOTS)} snapshots.")


if __name__ == "__main__":
    seed_db()
